# Generated by Django 5.0.6 on 2024-08-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('join', 'Join'), ('leave', 'Leave')], default='user', max_length=10),
        ),
    ]
