# Generated by Django 5.0.6 on 2024-09-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='chat_room',
        ),
        migrations.RenameField(
            model_name='chatroomuser',
            old_name='room',
            new_name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='chatroomuser',
            name='left_at',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
