# Generated by Django 3.2.8 on 2024-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
