# Generated by Django 3.2.8 on 2024-06-28 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='tip_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='tip_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
