# Generated by Django 3.2.8 on 2024-06-12 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.CharField(max_length=128)),
                ('diameter', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.FloatField()),
                ('terrain', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=32)),
                ('hair_color', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex08.planets', to_field='name')),
            ],
        ),
    ]
