# Generated by Django 3.2.8 on 2024-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
