# Generated by Django 3.2.8 on 2024-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0003_alter_planets_surface_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='orbital_period',
            field=models.IntegerField(null=True),
        ),
    ]
