# Generated by Django 3.2.8 on 2024-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0005_alter_planets_rotation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='climate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
