# Generated by Django 3.2.8 on 2024-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0006_alter_planets_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='diameter',
            field=models.IntegerField(null=True),
        ),
    ]
