# Generated by Django 3.2.8 on 2024-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0007_alter_planets_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='terrain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
