# Generated by Django 3.2.8 on 2024-06-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0008_alter_planets_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='ex09.planets'),
        ),
    ]
