# Generated by Django 3.2.8 on 2024-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0011_alter_people_mass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
